In [ ]:
import numpy as np

arr = np.array([2, 5, 10])
print(arr)
print(type(arr))

arr2d = np.array([[2, 3], [9, 10], [4, 7], [10, 12]])
print(arr2d)
print(type(arr2d))

print(arr + 1)
print(arr * 2)

print(np.sum(arr))
print(np.median(arr))
print(np.mean(arr))
print(np.std(arr))
print(np.var(arr))
print(np.min(arr))
print(np.max(arr))

print(np.sort(arr))
print(np.unique(arr)) # similar to set

# list
list = [2, 3, 6]
print(list * 2)

[ 2  5 10]
<class 'numpy.ndarray'>
[[ 2  3]
 [ 9 10]
 [ 4  7]
 [10 12]]
<class 'numpy.ndarray'>
[ 3  6 11]
[ 4 10 20]
17
5.0
5.666666666666667
3.2998316455372216
10.888888888888888
2
10
[ 2  5 10]
[ 2  5 10]
[2, 3, 6, 2, 3, 6]
